### ISSUE TITLE
Error - Conditional Binary Operator Expected

### ISSUE THREAD

**Issue by tdaubs** [chnm/WP-Static#1]
Really like the idea of this script but am having some trouble getting it to work.

I'm getting the following error...

./wpstatic: line 121: conditional binary operator expected

Any ideas?

**Comment by RandallKent** [comment]
@tdaubs - Are you still having issues with this? What flag(s) are you passing?

**Comment by tdaubs** [comment]
Sorry, I posted the question quite a while back and don't even remember what is was about.
